
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Notebook networkmanagernotebook;
	private global::Gtk.Fixed networkmanagerFix;
	private global::Gtk.Label newmachinelbl;
	private global::Gtk.Entry entryNewMachine;
	private global::Gtk.Label hostselect;
	private global::Gtk.ComboBox comboboxSelectHost;
	private global::Gtk.Label hostPasswordLbl;
	private global::Gtk.Entry hostpasswordEntry;
	private global::Gtk.Button setPasswdbt;
	private global::Gtk.Button resetPasswd;
	private global::Gtk.Button btSSH;
	private global::Gtk.Button btPing;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Button addnewcomputer;
	private global::Gtk.ScrolledWindow consoleOutput;
	private global::Gtk.TextView textviewConsoleOutput;
	private global::Gtk.Label consoleOutput1;
	private global::Gtk.ScrolledWindow textviewConsoleInput;
	private global::Gtk.TextView textview1;
	private global::Gtk.Label labelConsoleInput;
	private global::Gtk.Label NetworkComputerTab;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Label label1;
	private global::Gtk.Fixed updatemanagerFix;
	private global::Gtk.Label labelPackages;
	private global::Gtk.ComboBoxEntry comboPackagesForUpdate;
	private global::Gtk.Label updatemanagertab;
	private global::Gtk.Fixed virusscannerFix;
	private global::Gtk.Label VirusScannerTab;
	private global::Gtk.MenuBar menubar1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("OpenWeasel Update Manager");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.WidthRequest = 800;
		this.fixed1.HeightRequest = 590;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.networkmanagernotebook = new global::Gtk.Notebook ();
		this.networkmanagernotebook.WidthRequest = 800;
		this.networkmanagernotebook.HeightRequest = 567;
		this.networkmanagernotebook.CanFocus = true;
		this.networkmanagernotebook.Name = "networkmanagernotebook";
		this.networkmanagernotebook.CurrentPage = 0;
		// Container child networkmanagernotebook.Gtk.Notebook+NotebookChild
		this.networkmanagerFix = new global::Gtk.Fixed ();
		this.networkmanagerFix.Name = "networkmanagerFix";
		this.networkmanagerFix.HasWindow = false;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.newmachinelbl = new global::Gtk.Label ();
		this.newmachinelbl.Name = "newmachinelbl";
		this.newmachinelbl.LabelProp = global::Mono.Unix.Catalog.GetString ("New Machine");
		this.networkmanagerFix.Add (this.newmachinelbl);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.newmachinelbl]));
		w2.X = 24;
		w2.Y = 254;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.entryNewMachine = new global::Gtk.Entry ();
		this.entryNewMachine.CanFocus = true;
		this.entryNewMachine.Name = "entryNewMachine";
		this.entryNewMachine.IsEditable = true;
		this.entryNewMachine.InvisibleChar = '●';
		this.networkmanagerFix.Add (this.entryNewMachine);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.entryNewMachine]));
		w3.X = 10;
		w3.Y = 270;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.hostselect = new global::Gtk.Label ();
		this.hostselect.Name = "hostselect";
		this.hostselect.LabelProp = global::Mono.Unix.Catalog.GetString ("Select a Host");
		this.networkmanagerFix.Add (this.hostselect);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.hostselect]));
		w4.X = 18;
		w4.Y = 20;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.comboboxSelectHost = global::Gtk.ComboBox.NewText ();
		this.comboboxSelectHost.WidthRequest = 157;
		this.comboboxSelectHost.Name = "comboboxSelectHost";
		this.networkmanagerFix.Add (this.comboboxSelectHost);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.comboboxSelectHost]));
		w5.X = 11;
		w5.Y = 34;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.hostPasswordLbl = new global::Gtk.Label ();
		this.hostPasswordLbl.Name = "hostPasswordLbl";
		this.hostPasswordLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Host Password");
		this.networkmanagerFix.Add (this.hostPasswordLbl);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.hostPasswordLbl]));
		w6.X = 20;
		w6.Y = 69;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.hostpasswordEntry = new global::Gtk.Entry ();
		this.hostpasswordEntry.CanFocus = true;
		this.hostpasswordEntry.Name = "hostpasswordEntry";
		this.hostpasswordEntry.IsEditable = true;
		this.hostpasswordEntry.Visibility = false;
		this.hostpasswordEntry.InvisibleChar = '●';
		this.networkmanagerFix.Add (this.hostpasswordEntry);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.hostpasswordEntry]));
		w7.X = 10;
		w7.Y = 85;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.setPasswdbt = new global::Gtk.Button ();
		this.setPasswdbt.CanFocus = true;
		this.setPasswdbt.Name = "setPasswdbt";
		this.setPasswdbt.UseUnderline = true;
		this.setPasswdbt.Label = global::Mono.Unix.Catalog.GetString ("Set Password");
		this.networkmanagerFix.Add (this.setPasswdbt);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.setPasswdbt]));
		w8.X = 93;
		w8.Y = 113;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.resetPasswd = new global::Gtk.Button ();
		this.resetPasswd.CanFocus = true;
		this.resetPasswd.Name = "resetPasswd";
		this.resetPasswd.UseUnderline = true;
		this.resetPasswd.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.networkmanagerFix.Add (this.resetPasswd);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.resetPasswd]));
		w9.X = 9;
		w9.Y = 113;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.btSSH = new global::Gtk.Button ();
		this.btSSH.WidthRequest = 170;
		this.btSSH.CanFocus = true;
		this.btSSH.Events = ((global::Gdk.EventMask)(256));
		this.btSSH.Name = "btSSH";
		this.btSSH.UseUnderline = true;
		this.btSSH.Label = global::Mono.Unix.Catalog.GetString ("Launch SSH");
		this.networkmanagerFix.Add (this.btSSH);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.btSSH]));
		w10.X = 6;
		w10.Y = 182;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.btPing = new global::Gtk.Button ();
		this.btPing.WidthRequest = 170;
		this.btPing.CanFocus = true;
		this.btPing.Events = ((global::Gdk.EventMask)(256));
		this.btPing.Name = "btPing";
		this.btPing.UseUnderline = true;
		this.btPing.Label = global::Mono.Unix.Catalog.GetString ("Ping");
		this.networkmanagerFix.Add (this.btPing);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.btPing]));
		w11.X = 6;
		w11.Y = 158;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.WidthRequest = 760;
		this.hseparator1.Name = "hseparator1";
		this.networkmanagerFix.Add (this.hseparator1);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.hseparator1]));
		w12.X = 1;
		w12.Y = 512;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.addnewcomputer = new global::Gtk.Button ();
		this.addnewcomputer.WidthRequest = 47;
		this.addnewcomputer.CanFocus = true;
		this.addnewcomputer.Name = "addnewcomputer";
		this.addnewcomputer.UseUnderline = true;
		this.addnewcomputer.Label = global::Mono.Unix.Catalog.GetString ("Add");
		this.networkmanagerFix.Add (this.addnewcomputer);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.addnewcomputer]));
		w13.X = 122;
		w13.Y = 301;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.consoleOutput = new global::Gtk.ScrolledWindow ();
		this.consoleOutput.WidthRequest = 777;
		this.consoleOutput.HeightRequest = 141;
		this.consoleOutput.Name = "consoleOutput";
		this.consoleOutput.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child consoleOutput.Gtk.Container+ContainerChild
		this.textviewConsoleOutput = new global::Gtk.TextView ();
		this.textviewConsoleOutput.CanFocus = true;
		this.textviewConsoleOutput.Name = "textviewConsoleOutput";
		this.consoleOutput.Add (this.textviewConsoleOutput);
		this.networkmanagerFix.Add (this.consoleOutput);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.consoleOutput]));
		w15.X = 9;
		w15.Y = 358;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.consoleOutput1 = new global::Gtk.Label ();
		this.consoleOutput1.Name = "consoleOutput1";
		this.consoleOutput1.LabelProp = global::Mono.Unix.Catalog.GetString ("Console Output");
		this.networkmanagerFix.Add (this.consoleOutput1);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.consoleOutput1]));
		w16.X = 14;
		w16.Y = 340;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.textviewConsoleInput = new global::Gtk.ScrolledWindow ();
		this.textviewConsoleInput.WidthRequest = 570;
		this.textviewConsoleInput.HeightRequest = 271;
		this.textviewConsoleInput.Name = "textviewConsoleInput";
		this.textviewConsoleInput.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child textviewConsoleInput.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textviewConsoleInput.Add (this.textview1);
		this.networkmanagerFix.Add (this.textviewConsoleInput);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.textviewConsoleInput]));
		w18.X = 215;
		w18.Y = 38;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.labelConsoleInput = new global::Gtk.Label ();
		this.labelConsoleInput.Name = "labelConsoleInput";
		this.labelConsoleInput.LabelProp = global::Mono.Unix.Catalog.GetString ("SSH Console");
		this.networkmanagerFix.Add (this.labelConsoleInput);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.labelConsoleInput]));
		w19.X = 457;
		w19.Y = 20;
		this.networkmanagernotebook.Add (this.networkmanagerFix);
		// Notebook tab
		this.NetworkComputerTab = new global::Gtk.Label ();
		this.NetworkComputerTab.Name = "NetworkComputerTab";
		this.NetworkComputerTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Network Manager");
		this.networkmanagernotebook.SetTabLabel (this.networkmanagerFix, this.NetworkComputerTab);
		this.NetworkComputerTab.ShowAll ();
		// Container child networkmanagernotebook.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.networkmanagernotebook.Add (this.fixed2);
		global::Gtk.Notebook.NotebookChild w21 = ((global::Gtk.Notebook.NotebookChild)(this.networkmanagernotebook [this.fixed2]));
		w21.Position = 1;
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Network Map");
		this.networkmanagernotebook.SetTabLabel (this.fixed2, this.label1);
		this.label1.ShowAll ();
		// Container child networkmanagernotebook.Gtk.Notebook+NotebookChild
		this.updatemanagerFix = new global::Gtk.Fixed ();
		this.updatemanagerFix.Name = "updatemanagerFix";
		this.updatemanagerFix.HasWindow = false;
		// Container child updatemanagerFix.Gtk.Fixed+FixedChild
		this.labelPackages = new global::Gtk.Label ();
		this.labelPackages.Name = "labelPackages";
		this.labelPackages.LabelProp = global::Mono.Unix.Catalog.GetString ("Packages");
		this.updatemanagerFix.Add (this.labelPackages);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.updatemanagerFix [this.labelPackages]));
		w22.X = 27;
		w22.Y = 29;
		// Container child updatemanagerFix.Gtk.Fixed+FixedChild
		this.comboPackagesForUpdate = global::Gtk.ComboBoxEntry.NewText ();
		this.comboPackagesForUpdate.Name = "comboPackagesForUpdate";
		this.updatemanagerFix.Add (this.comboPackagesForUpdate);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.updatemanagerFix [this.comboPackagesForUpdate]));
		w23.X = 22;
		w23.Y = 45;
		this.networkmanagernotebook.Add (this.updatemanagerFix);
		global::Gtk.Notebook.NotebookChild w24 = ((global::Gtk.Notebook.NotebookChild)(this.networkmanagernotebook [this.updatemanagerFix]));
		w24.Position = 2;
		// Notebook tab
		this.updatemanagertab = new global::Gtk.Label ();
		this.updatemanagertab.Name = "updatemanagertab";
		this.updatemanagertab.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Manager");
		this.networkmanagernotebook.SetTabLabel (this.updatemanagerFix, this.updatemanagertab);
		this.updatemanagertab.ShowAll ();
		// Container child networkmanagernotebook.Gtk.Notebook+NotebookChild
		this.virusscannerFix = new global::Gtk.Fixed ();
		this.virusscannerFix.Name = "virusscannerFix";
		this.virusscannerFix.HasWindow = false;
		this.networkmanagernotebook.Add (this.virusscannerFix);
		global::Gtk.Notebook.NotebookChild w25 = ((global::Gtk.Notebook.NotebookChild)(this.networkmanagernotebook [this.virusscannerFix]));
		w25.Position = 3;
		// Notebook tab
		this.VirusScannerTab = new global::Gtk.Label ();
		this.VirusScannerTab.Name = "VirusScannerTab";
		this.VirusScannerTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Virus Scanner");
		this.networkmanagernotebook.SetTabLabel (this.virusscannerFix, this.VirusScannerTab);
		this.VirusScannerTab.ShowAll ();
		this.fixed1.Add (this.networkmanagernotebook);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.networkmanagernotebook]));
		w26.Y = 22;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.WidthRequest = 800;
		this.menubar1.Name = "menubar1";
		this.fixed1.Add (this.menubar1);
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 590;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
