
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action UpdateManagerAction;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action ViewAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action SaveAction;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Notebook networkmanagernotebook;
	private global::Gtk.Fixed networkmanagerFix;
	private global::Gtk.Label newmachinelbl;
	private global::Gtk.Entry newMachine;
	private global::Gtk.Button addnewcomputer;
	private global::Gtk.Label hostselect;
	private global::Gtk.ComboBox combobox1;
	private global::Gtk.Label hostPasswordLbl;
	private global::Gtk.Entry hostpasswordEntry;
	private global::Gtk.Button setPasswdbt;
	private global::Gtk.Button resetPasswd;
	private global::Gtk.Button sshButton;
	private global::Gtk.Button pingButton;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textarea;
	private global::Gtk.Label label4;
	private global::Gtk.Label TitleLb;
	private global::Gtk.Entry titleEntry;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Button networkApplyBT;
	private global::Gtk.Button saveLogBT;
	private global::Gtk.FileChooserButton filechooserbutton1;
	private global::Gtk.Label NetworkComputerTab;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Label label1;
	private global::Gtk.Fixed updatemanagerFix;
	private global::Gtk.Label updatemanagertab;
	private global::Gtk.Fixed virusscannerFix;
	private global::Gtk.Label VirusScannerTab;
	private global::Gtk.MenuBar MenuBar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.UpdateManagerAction = new global::Gtk.Action ("UpdateManagerAction", global::Mono.Unix.Catalog.GetString ("Update Manager"), null, null);
		this.UpdateManagerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Update Manager");
		w1.Add (this.UpdateManagerAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("OpenWeasel Update Manager");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.WidthRequest = 800;
		this.fixed1.HeightRequest = 590;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.networkmanagernotebook = new global::Gtk.Notebook ();
		this.networkmanagernotebook.WidthRequest = 800;
		this.networkmanagernotebook.HeightRequest = 567;
		this.networkmanagernotebook.CanFocus = true;
		this.networkmanagernotebook.Name = "networkmanagernotebook";
		this.networkmanagernotebook.CurrentPage = 0;
		// Container child networkmanagernotebook.Gtk.Notebook+NotebookChild
		this.networkmanagerFix = new global::Gtk.Fixed ();
		this.networkmanagerFix.Name = "networkmanagerFix";
		this.networkmanagerFix.HasWindow = false;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.newmachinelbl = new global::Gtk.Label ();
		this.newmachinelbl.Name = "newmachinelbl";
		this.newmachinelbl.LabelProp = global::Mono.Unix.Catalog.GetString ("New Machine");
		this.networkmanagerFix.Add (this.newmachinelbl);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.newmachinelbl]));
		w2.X = 24;
		w2.Y = 415;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.newMachine = new global::Gtk.Entry ();
		this.newMachine.CanFocus = true;
		this.newMachine.Name = "newMachine";
		this.newMachine.IsEditable = true;
		this.newMachine.InvisibleChar = '●';
		this.networkmanagerFix.Add (this.newMachine);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.newMachine]));
		w3.X = 22;
		w3.Y = 429;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.addnewcomputer = new global::Gtk.Button ();
		this.addnewcomputer.WidthRequest = 47;
		this.addnewcomputer.CanFocus = true;
		this.addnewcomputer.Name = "addnewcomputer";
		this.addnewcomputer.UseUnderline = true;
		this.addnewcomputer.Label = global::Mono.Unix.Catalog.GetString ("Add");
		this.networkmanagerFix.Add (this.addnewcomputer);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.addnewcomputer]));
		w4.X = 135;
		w4.Y = 455;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.hostselect = new global::Gtk.Label ();
		this.hostselect.Name = "hostselect";
		this.hostselect.LabelProp = global::Mono.Unix.Catalog.GetString ("Select a Host");
		this.networkmanagerFix.Add (this.hostselect);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.hostselect]));
		w5.X = 18;
		w5.Y = 20;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.WidthRequest = 157;
		this.combobox1.Name = "combobox1";
		this.networkmanagerFix.Add (this.combobox1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.combobox1]));
		w6.X = 11;
		w6.Y = 34;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.hostPasswordLbl = new global::Gtk.Label ();
		this.hostPasswordLbl.Name = "hostPasswordLbl";
		this.hostPasswordLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Host Password");
		this.networkmanagerFix.Add (this.hostPasswordLbl);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.hostPasswordLbl]));
		w7.X = 20;
		w7.Y = 69;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.hostpasswordEntry = new global::Gtk.Entry ();
		this.hostpasswordEntry.CanFocus = true;
		this.hostpasswordEntry.Name = "hostpasswordEntry";
		this.hostpasswordEntry.IsEditable = true;
		this.hostpasswordEntry.Visibility = false;
		this.hostpasswordEntry.InvisibleChar = '●';
		this.networkmanagerFix.Add (this.hostpasswordEntry);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.hostpasswordEntry]));
		w8.X = 10;
		w8.Y = 85;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.setPasswdbt = new global::Gtk.Button ();
		this.setPasswdbt.CanFocus = true;
		this.setPasswdbt.Name = "setPasswdbt";
		this.setPasswdbt.UseUnderline = true;
		this.setPasswdbt.Label = global::Mono.Unix.Catalog.GetString ("Set Password");
		this.networkmanagerFix.Add (this.setPasswdbt);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.setPasswdbt]));
		w9.X = 93;
		w9.Y = 113;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.resetPasswd = new global::Gtk.Button ();
		this.resetPasswd.CanFocus = true;
		this.resetPasswd.Name = "resetPasswd";
		this.resetPasswd.UseUnderline = true;
		this.resetPasswd.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.networkmanagerFix.Add (this.resetPasswd);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.resetPasswd]));
		w10.X = 9;
		w10.Y = 113;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.sshButton = new global::Gtk.Button ();
		this.sshButton.WidthRequest = 170;
		this.sshButton.CanFocus = true;
		this.sshButton.Name = "sshButton";
		this.sshButton.UseUnderline = true;
		this.sshButton.Label = global::Mono.Unix.Catalog.GetString ("Launch SSH");
		this.networkmanagerFix.Add (this.sshButton);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.sshButton]));
		w11.X = 6;
		w11.Y = 182;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.pingButton = new global::Gtk.Button ();
		this.pingButton.WidthRequest = 170;
		this.pingButton.CanFocus = true;
		this.pingButton.Name = "pingButton";
		this.pingButton.UseUnderline = true;
		this.pingButton.Label = global::Mono.Unix.Catalog.GetString ("Ping");
		this.networkmanagerFix.Add (this.pingButton);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.pingButton]));
		w12.X = 6;
		w12.Y = 158;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textarea = new global::Gtk.TextView ();
		this.textarea.WidthRequest = 270;
		this.textarea.HeightRequest = 374;
		this.textarea.CanFocus = true;
		this.textarea.Name = "textarea";
		this.GtkScrolledWindow.Add (this.textarea);
		this.networkmanagerFix.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.GtkScrolledWindow]));
		w14.X = 198;
		w14.Y = 62;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Issues and Changes Log");
		this.networkmanagerFix.Add (this.label4);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.label4]));
		w15.X = 259;
		w15.Y = 20;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.TitleLb = new global::Gtk.Label ();
		this.TitleLb.Name = "TitleLb";
		this.TitleLb.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
		this.networkmanagerFix.Add (this.TitleLb);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.TitleLb]));
		w16.X = 202;
		w16.Y = 41;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.titleEntry = new global::Gtk.Entry ();
		this.titleEntry.CanFocus = true;
		this.titleEntry.Name = "titleEntry";
		this.titleEntry.IsEditable = true;
		this.titleEntry.InvisibleChar = '●';
		this.networkmanagerFix.Add (this.titleEntry);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.titleEntry]));
		w17.X = 223;
		w17.Y = 36;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.WidthRequest = 760;
		this.hseparator1.Name = "hseparator1";
		this.networkmanagerFix.Add (this.hseparator1);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.hseparator1]));
		w18.X = 1;
		w18.Y = 512;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.networkApplyBT = new global::Gtk.Button ();
		this.networkApplyBT.WidthRequest = 100;
		this.networkApplyBT.CanFocus = true;
		this.networkApplyBT.Name = "networkApplyBT";
		this.networkApplyBT.UseUnderline = true;
		this.networkApplyBT.Label = global::Mono.Unix.Catalog.GetString ("Apply");
		this.networkmanagerFix.Add (this.networkApplyBT);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.networkApplyBT]));
		w19.X = 682;
		w19.Y = 484;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.saveLogBT = new global::Gtk.Button ();
		this.saveLogBT.CanFocus = true;
		this.saveLogBT.Name = "saveLogBT";
		this.saveLogBT.UseUnderline = true;
		this.saveLogBT.Label = global::Mono.Unix.Catalog.GetString ("Save Log");
		this.networkmanagerFix.Add (this.saveLogBT);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.saveLogBT]));
		w20.X = 418;
		w20.Y = 455;
		// Container child networkmanagerFix.Gtk.Fixed+FixedChild
		this.filechooserbutton1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton1.Name = "filechooserbutton1";
		this.networkmanagerFix.Add (this.filechooserbutton1);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.networkmanagerFix [this.filechooserbutton1]));
		w21.X = 657;
		w21.Y = 49;
		this.networkmanagernotebook.Add (this.networkmanagerFix);
		// Notebook tab
		this.NetworkComputerTab = new global::Gtk.Label ();
		this.NetworkComputerTab.Name = "NetworkComputerTab";
		this.NetworkComputerTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Network Manager");
		this.networkmanagernotebook.SetTabLabel (this.networkmanagerFix, this.NetworkComputerTab);
		this.NetworkComputerTab.ShowAll ();
		// Container child networkmanagernotebook.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.networkmanagernotebook.Add (this.fixed2);
		global::Gtk.Notebook.NotebookChild w23 = ((global::Gtk.Notebook.NotebookChild)(this.networkmanagernotebook [this.fixed2]));
		w23.Position = 1;
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Network Map");
		this.networkmanagernotebook.SetTabLabel (this.fixed2, this.label1);
		this.label1.ShowAll ();
		// Container child networkmanagernotebook.Gtk.Notebook+NotebookChild
		this.updatemanagerFix = new global::Gtk.Fixed ();
		this.updatemanagerFix.Name = "updatemanagerFix";
		this.updatemanagerFix.HasWindow = false;
		this.networkmanagernotebook.Add (this.updatemanagerFix);
		global::Gtk.Notebook.NotebookChild w24 = ((global::Gtk.Notebook.NotebookChild)(this.networkmanagernotebook [this.updatemanagerFix]));
		w24.Position = 2;
		// Notebook tab
		this.updatemanagertab = new global::Gtk.Label ();
		this.updatemanagertab.Name = "updatemanagertab";
		this.updatemanagertab.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Manager");
		this.networkmanagernotebook.SetTabLabel (this.updatemanagerFix, this.updatemanagertab);
		this.updatemanagertab.ShowAll ();
		// Container child networkmanagernotebook.Gtk.Notebook+NotebookChild
		this.virusscannerFix = new global::Gtk.Fixed ();
		this.virusscannerFix.Name = "virusscannerFix";
		this.virusscannerFix.HasWindow = false;
		this.networkmanagernotebook.Add (this.virusscannerFix);
		global::Gtk.Notebook.NotebookChild w25 = ((global::Gtk.Notebook.NotebookChild)(this.networkmanagernotebook [this.virusscannerFix]));
		w25.Position = 3;
		// Notebook tab
		this.VirusScannerTab = new global::Gtk.Label ();
		this.VirusScannerTab.Name = "VirusScannerTab";
		this.VirusScannerTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Virus Scanner");
		this.networkmanagernotebook.SetTabLabel (this.virusscannerFix, this.VirusScannerTab);
		this.VirusScannerTab.ShowAll ();
		this.fixed1.Add (this.networkmanagernotebook);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.networkmanagernotebook]));
		w26.Y = 22;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><menubar name='MenuBar'><menu name='FileAction' action='FileAction'><menuitem name='SaveAction' action='SaveAction'/></menu><menu name='ViewAction' action='ViewAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
		this.MenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MenuBar")));
		this.MenuBar.WidthRequest = 800;
		this.MenuBar.Name = "MenuBar";
		this.fixed1.Add (this.MenuBar);
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 590;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
